language: python

python: 
  - "2.7"
env: 
  global: 
     - secure: PiFrrcDhq/jJuIcE/bnhc7YJDonOa8QbF/PvCpoI8uSqlNXCObnmRy69edGjFrUpge+u13TTm/D1FN70klktpIvaKcYedUIQ3db9MoHulkdaRrS5WoJpM5lYQr0SES72w5Ul8ia2E9wPAdhfpH2ZCFkDPkLz2Fr1xndE7nmjHzQ=

branches: 
  only: 
  - master

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq gsl-bin libgsl0-dev swig libblas-dev libatlas-dev liblapack-dev gfortran
  - sudo apt-get install -qq r-base r-base-dev

install: 
  - pip install numpy --use-mirrors --upgrade
  - pip install scipy --use-mirrors --upgrade
  - pip install pandas --use-mirrors --upgrade
  - pip install matplotlib --use-mirrors --upgrade
  - pip install pytest --use-mirrors --upgrade
  - pip install ipython[all] --upgrade
  - pip install rpy2
  - python setup.py build
  - python setup.py install

script: 
  - cd test
  - py.test -v test*.py
  - cd ..
  - sh tools/commit_from_travis.sh


