language: python

python: 
  - "2.7"
env: 
  global: 
     - secure: PiFrrcDhq/jJuIcE/bnhc7YJDonOa8QbF/PvCpoI8uSqlNXCObnmRy69edGjFrUpge+u13TTm/D1FN70klktpIvaKcYedUIQ3db9MoHulkdaRrS5WoJpM5lYQr0SES72w5Ul8ia2E9wPAdhfpH2ZCFkDPkLz2Fr1xndE7nmjHzQ=

branches: 
  only: 
  - master

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq gsl-bin libgsl0-dev swig libblas-dev libatlas-dev liblapack-dev gfortran

install: 
  - pip -q install numpy --use-mirrors --upgrade
  - pip -q install scipy --use-mirrors --upgrade
  - pip -q install pandas --use-mirrors --upgrade
  - pip -q install matplotlib --use-mirrors --upgrade
  - pip -q install pytest --use-mirrors --upgrade
  - pip -q install ipython --upgrade
  - python setup.py build
  - python setup.py install

script: 
  - cd test; py.test -v *.py; cd ..
  - sh tools/commit_from_travis.sh


