language: python
python:
  - "2.7"

# setup dependencies for python-packages
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gsl-bin libgsl0-dev swig libblas-dev libatlas-dev liblapack-dev gfortran

# command to install dependencies
install:
  - "pip install numpy --use-mirrors --upgrade"
  - "pip install scipy --use-mirrors --upgrade"
  - "pip install pandas --use-mirrors --upgrade"
  - "pip install matplotlib --use-mirrors --upgrade"
  - "pip install pytest --use-mirrors --upgrade"
  - "python setup.py install"

# command to run tests
script: py.test -v test/*.py