language: python
python:
  - "2.6"
  - "2.7"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gsl-bin libgsl0-dev swig python-numpy python-scipy

# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: nosetests test